Search.appendIndex(
    [
                {
            "fqsen": "\\DSLB_FILE",
            "name": "DSLB_FILE",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_FILE"
        },                {
            "fqsen": "\\DSLB_VERSION",
            "name": "DSLB_VERSION",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_VERSION"
        },                {
            "fqsen": "\\DSLB_PLUGIN_NAME",
            "name": "DSLB_PLUGIN_NAME",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_PLUGIN_NAME"
        },                {
            "fqsen": "\\DSLB_TOKEN",
            "name": "DSLB_TOKEN",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_TOKEN"
        },                {
            "fqsen": "\\DSLB_PATH",
            "name": "DSLB_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_PATH"
        },                {
            "fqsen": "\\DSLB_URL",
            "name": "DSLB_URL",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_URL"
        },                {
            "fqsen": "\\DSLB_ASSETS_PATH",
            "name": "DSLB_ASSETS_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_ASSETS_PATH"
        },                {
            "fqsen": "\\DSLB_ASSETS_URL",
            "name": "DSLB_ASSETS_URL",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_ASSETS_URL"
        },                {
            "fqsen": "\\DSLB_INCLUDES_PATH",
            "name": "DSLB_INCLUDES_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_INCLUDES_PATH"
        },                {
            "fqsen": "\\DSLB_LIBRARY_PATH",
            "name": "DSLB_LIBRARY_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_DSLB_LIBRARY_PATH"
        },                {
            "fqsen": "\\dslb_load_plugin_textdomain\u0028\u0029",
            "name": "dslb_load_plugin_textdomain",
            "summary": "Load\u0020Plugin\u0020textdomain.",
            "url": "namespaces/default.html#function_dslb_load_plugin_textdomain"
        },                {
            "fqsen": "\\dslb_php_version_check_fail\u0028\u0029",
            "name": "dslb_php_version_check_fail",
            "summary": "Plugin\u0020admin\u0020notice\u0020for\u0020minimum\u0020PHP\u0020version.",
            "url": "namespaces/default.html#function_dslb_php_version_check_fail"
        },                {
            "fqsen": "\\dslb_wp_version_check_fail\u0028\u0029",
            "name": "dslb_wp_version_check_fail",
            "summary": "Plugin\u0020admin\u0020notice\u0020for\u0020minimum\u0020WordPress\u0020version.",
            "url": "namespaces/default.html#function_dslb_wp_version_check_fail"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin",
            "name": "Admin",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Admin\u0020constructor.",
            "url": "classes/RahulK-DSLB-Admin.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003AadminInit\u0028\u0029",
            "name": "adminInit",
            "summary": "Method\u0020that\u0020is\u0020used\u0020on\u0020plugin\u0020initialization\u0020time",
            "url": "classes/RahulK-DSLB-Admin.html#method_adminInit"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Aadmin_enqueue_scripts\u0028\u0029",
            "name": "admin_enqueue_scripts",
            "summary": "Load\u0020admin\u0020Javascript.",
            "url": "classes/RahulK-DSLB-Admin.html#method_admin_enqueue_scripts"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Aadmin_enqueue_styles\u0028\u0029",
            "name": "admin_enqueue_styles",
            "summary": "Load\u0020admin\u0020CSS.",
            "url": "classes/RahulK-DSLB-Admin.html#method_admin_enqueue_styles"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Aplugin_action_links\u0028\u0029",
            "name": "plugin_action_links",
            "summary": "Show\u0020action\u0020links\u0020on\u0020the\u0020plugin\u0020screen.",
            "url": "classes/RahulK-DSLB-Admin.html#method_plugin_action_links"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Aadd_menu\u0028\u0029",
            "name": "add_menu",
            "summary": "Add\u0020Admin\u0020Menu",
            "url": "classes/RahulK-DSLB-Admin.html#method_add_menu"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Asettings_UI\u0028\u0029",
            "name": "settings_UI",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#method_settings_UI"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003Aadmin_body_class\u0028\u0029",
            "name": "admin_body_class",
            "summary": "Add\u0020custom\u0020classes\u0020to\u0020the\u0020HTML\u0020body\u0020tag",
            "url": "classes/RahulK-DSLB-Admin.html#method_admin_body_class"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024script_suffix",
            "name": "script_suffix",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_script_suffix"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024dir",
            "name": "dir",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_dir"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Admin\u003A\u003A\u0024hook_suffix",
            "name": "hook_suffix",
            "summary": "",
            "url": "classes/RahulK-DSLB-Admin.html#property_hook_suffix"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader",
            "name": "Autoloader",
            "summary": "Plugin\u0020autoloader.",
            "url": "classes/RahulK-DSLB-Autoloader.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020autoloader.",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_run"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Aget_classes_aliases\u0028\u0029",
            "name": "get_classes_aliases",
            "summary": "Get\u0020classes\u0020aliases.",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_get_classes_aliases"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Aget_classes_map\u0028\u0029",
            "name": "get_classes_map",
            "summary": "",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_get_classes_map"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Ainit_classes_map\u0028\u0029",
            "name": "init_classes_map",
            "summary": "",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_init_classes_map"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Ainit_classes_aliases\u0028\u0029",
            "name": "init_classes_aliases",
            "summary": "",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_init_classes_aliases"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Aload_class\u0028\u0029",
            "name": "load_class",
            "summary": "Load\u0020class.",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_load_class"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003Aautoload\u0028\u0029",
            "name": "autoload",
            "summary": "Autoload.",
            "url": "classes/RahulK-DSLB-Autoloader.html#method_autoload"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003A\u0024classes_map",
            "name": "classes_map",
            "summary": "Classes\u0020map.",
            "url": "classes/RahulK-DSLB-Autoloader.html#property_classes_map"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003A\u0024classes_aliases",
            "name": "classes_aliases",
            "summary": "Classes\u0020aliases.",
            "url": "classes/RahulK-DSLB-Autoloader.html#property_classes_aliases"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003A\u0024default_path",
            "name": "default_path",
            "summary": "Default\u0020path\u0020for\u0020autoloader.",
            "url": "classes/RahulK-DSLB-Autoloader.html#property_default_path"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Autoloader\u003A\u003A\u0024default_namespace",
            "name": "default_namespace",
            "summary": "Default\u0020namespace\u0020for\u0020autoloader.",
            "url": "classes/RahulK-DSLB-Autoloader.html#property_default_namespace"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler",
            "name": "AjaxHandler",
            "summary": "Ajax\u0020Handler\u0020for\u0020Doctors\u0020Slot\u0020Booking\u0020Plugin.",
            "url": "classes/RahulK-DSLB-AjaxHandler.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Admin\u0020constructor.",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003Aget_available_days\u0028\u0029",
            "name": "get_available_days",
            "summary": "Get\u0020available\u0020days\u0020for\u0020a\u0020selected\u0020doctor.",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#method_get_available_days"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003Aget_available_slots\u0028\u0029",
            "name": "get_available_slots",
            "summary": "Get\u0020available\u0020time\u0020slots\u0020for\u0020a\u0020selected\u0020doctor\u0020and\u0020date.",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#method_get_available_slots"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003Abook_appointment\u0028\u0029",
            "name": "book_appointment",
            "summary": "Submit\u0020a\u0020booking.",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#method_book_appointment"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\AjaxHandler\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-AjaxHandler.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt",
            "name": "Cpt",
            "summary": "",
            "url": "classes/RahulK-DSLB-Cpt.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Admin\u0020constructor.",
            "url": "classes/RahulK-DSLB-Cpt.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020custom\u0020post\u0020type.",
            "url": "classes/RahulK-DSLB-Cpt.html#method_init"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-Cpt.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-Cpt.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-Cpt.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Cpt\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-Cpt.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail",
            "name": "SendMail",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003Aset_header\u0028\u0029",
            "name": "set_header",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#method_set_header"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003Aset_footer\u0028\u0029",
            "name": "set_footer",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#method_set_footer"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#method_send"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003Aget_template\u0028\u0029",
            "name": "get_template",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#method_get_template"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024to",
            "name": "to",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_to"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_subject"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_content"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_headers"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024attachments",
            "name": "attachments",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_attachments"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024email_header",
            "name": "email_header",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_email_header"
        },                {
            "fqsen": "\\RahulK\\DSLB\\SendMail\u003A\u003A\u0024email_footer",
            "name": "email_footer",
            "summary": "",
            "url": "classes/RahulK-DSLB-SendMail.html#property_email_footer"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post",
            "name": "Post",
            "summary": "",
            "url": "classes/RahulK-DSLB-Post.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Post\u0020constructor.",
            "url": "classes/RahulK-DSLB-Post.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003Asave_post\u0028\u0029",
            "name": "save_post",
            "summary": "Save\u0020post\u0020callback.",
            "url": "classes/RahulK-DSLB-Post.html#method_save_post"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003Asend_email_on_booking_status_change\u0028\u0029",
            "name": "send_email_on_booking_status_change",
            "summary": "Send\u0020email\u0020on\u0020booking\u0020status\u0020change.",
            "url": "classes/RahulK-DSLB-Post.html#method_send_email_on_booking_status_change"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-Post.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-Post.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-Post.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Post\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-Post.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes",
            "name": "Shortcodes",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Admin\u0020constructor.",
            "url": "classes/RahulK-DSLB-Shortcodes.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003Ainit_shortcodes\u0028\u0029",
            "name": "init_shortcodes",
            "summary": "Initialize\u0020shortcodes.",
            "url": "classes/RahulK-DSLB-Shortcodes.html#method_init_shortcodes"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003Ashow_booking_form\u0028\u0029",
            "name": "show_booking_form",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html#method_show_booking_form"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Shortcodes\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-Shortcodes.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Schema",
            "name": "Schema",
            "summary": "",
            "url": "classes/RahulK-DSLB-Schema.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Schema\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/RahulK-DSLB-Schema.html#method_init"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Schema\u003A\u003AgetConstant\u0028\u0029",
            "name": "getConstant",
            "summary": "Get\u0020schema\u0020constant\u0020by\u0020key.",
            "url": "classes/RahulK-DSLB-Schema.html#method_getConstant"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Schema\u003A\u003A\u0024constants",
            "name": "constants",
            "summary": "",
            "url": "classes/RahulK-DSLB-Schema.html#property_constants"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Schema\u003A\u003A\u0024service_labels",
            "name": "service_labels",
            "summary": "",
            "url": "classes/RahulK-DSLB-Schema.html#property_service_labels"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes",
            "name": "MetaBoxes",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Admin\u0020constructor.",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Ameta_boxes\u0028\u0029",
            "name": "meta_boxes",
            "summary": "Add\u0020Meta\u0020Boxes",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_meta_boxes"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Ameta_box_doctor\u0028\u0029",
            "name": "meta_box_doctor",
            "summary": "Metabox\u0020for\u0020Doctor\u0020CPT",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_meta_box_doctor"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Ameta_box_booking\u0028\u0029",
            "name": "meta_box_booking",
            "summary": "Metabox\u0020for\u0020Booking\u0020CPT",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_meta_box_booking"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Adoctor_save_meta_boxes\u0028\u0029",
            "name": "doctor_save_meta_boxes",
            "summary": "Metaboxes\u0020Save\u0020for\u0020Doctor\u0020CPT",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_doctor_save_meta_boxes"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Abooking_save_meta_boxes\u0028\u0029",
            "name": "booking_save_meta_boxes",
            "summary": "Metaboxes\u0020Save\u0020for\u0020Booking\u0020CPT",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_booking_save_meta_boxes"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Abookings_columns\u0028\u0029",
            "name": "bookings_columns",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_bookings_columns"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Abookings_columns_content\u0028\u0029",
            "name": "bookings_columns_content",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_bookings_columns_content"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Aadd_bookings_filter_dropdown\u0028\u0029",
            "name": "add_bookings_filter_dropdown",
            "summary": "Add\u0020filter\u0020dropdown\u0020for\u0020bookings",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_add_bookings_filter_dropdown"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Afilter_bookings\u0028\u0029",
            "name": "filter_bookings",
            "summary": "Filter\u0020bookings\u0020based\u0020on\u0020selected\u0020status",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_filter_bookings"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003Afilter_bookings_search\u0028\u0029",
            "name": "filter_bookings_search",
            "summary": "Filter\u0020bookings\u0020search\u0020query",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#method_filter_bookings_search"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003A\u0024assets_url",
            "name": "assets_url",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#property_assets_url"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#property_version"
        },                {
            "fqsen": "\\RahulK\\DSLB\\MetaBoxes\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-MetaBoxes.html#property_token"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main",
            "name": "Main",
            "summary": "Doctors\u0020Slot\u0020Booking\u0020Plugin\u0020by\u0020RahulK",
            "url": "classes/RahulK-DSLB-Main.html"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Plugin\u0020constructor.\u002B",
            "url": "classes/RahulK-DSLB-Main.html#method___construct"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Ainstall\u0028\u0029",
            "name": "install",
            "summary": "Installation.\u0020Runs\u0020on\u0020activation.",
            "url": "classes/RahulK-DSLB-Main.html#method_install"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Adeactivation\u0028\u0029",
            "name": "deactivation",
            "summary": "Deactivation\u0020Hook",
            "url": "classes/RahulK-DSLB-Main.html#method_deactivation"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Aregister_autoloader\u0028\u0029",
            "name": "register_autoloader",
            "summary": "Register\u0020autoloader.",
            "url": "classes/RahulK-DSLB-Main.html#method_register_autoloader"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "Instance.",
            "url": "classes/RahulK-DSLB-Main.html#property_instance"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Init.",
            "url": "classes/RahulK-DSLB-Main.html#method_init"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Ainit_components\u0028\u0029",
            "name": "init_components",
            "summary": "Init\u0020components.",
            "url": "classes/RahulK-DSLB-Main.html#method_init_components"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003Aon_rest_api_init\u0028\u0029",
            "name": "on_rest_api_init",
            "summary": "",
            "url": "classes/RahulK-DSLB-Main.html#method_on_rest_api_init"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "Clone.",
            "url": "classes/RahulK-DSLB-Main.html#method___clone"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003A__wakeup\u0028\u0029",
            "name": "__wakeup",
            "summary": "Wakeup.",
            "url": "classes/RahulK-DSLB-Main.html#method___wakeup"
        },                {
            "fqsen": "\\RahulK\\DSLB\\Main\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/RahulK-DSLB-Main.html#property_token"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\RahulK\\DSLB",
            "name": "DSLB",
            "summary": "",
            "url": "namespaces/rahulk-dslb.html"
        },                {
            "fqsen": "\\RahulK",
            "name": "RahulK",
            "summary": "",
            "url": "namespaces/rahulk.html"
        }            ]
);
