name: Zip Plugin Release

on:
  workflow_dispatch:  # 👈 Allows manual trigger from GitHub UI
  push:
    tags:
      - '*'            # Optional: still runs on tag push

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin Version from PHP File
        id: get_version
        run: |
          version=$(grep -E "^\s*\*\s*Version:\s*" doctors-slot-booking.php | awk '{print $NF}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create ZIP Archive
        run: |
          mkdir -p output
          zip -r "output/doctors-slot-booking-${{ steps.get_version.outputs.version }}.zip" . \
            -x "*.git*" \
            -x ".github/*" \
            -x "output/*" \
            -x "*.md" \
            -x "*.zip" \
            -x ".DS_Store" \
            -x "readme.md" \
            -x "documentation/*" 

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doctors-slot-booking-${{ steps.get_version.outputs.version }}
          path: output/doctors-slot-booking-${{ steps.get_version.outputs.version }}.zip
