name: Auto Tag and Release Plugin

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push tags and create release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get plugin version from file
        id: get_version
        run: |
          version=$(grep -E "^\s*\*\s*Version:\s*" doctors-slot-booking.php | awk '{print $NF}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"

      - name: Create ZIP archive (no version in name)
        run: |
          mkdir -p dist
          zip -r "dist/doctors-slot-booking.zip" . \
            -x "*.git*" \
            -x ".github/*" \
            -x "dist/*" \
            -x "*.md" \
            -x "*.zip" \
            -x ".DS_Store"

      - name: Create GitHub Release & Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: dist/doctors-slot-booking.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
